(* This file is part of 'act'.

   Copyright (c) 2018, 2019 by Matt Windsor

   Permission is hereby granted, free of charge, to any person obtaining a
   copy of this software and associated documentation files (the
   "Software"), to deal in the Software without restriction, including
   without limitation the rights to use, copy, modify, merge, publish,
   distribute, sublicense, and/or sell copies of the Software, and to permit
   persons to whom the Software is furnished to do so, subject to the
   following conditions:

   The above copyright notice and this permission notice shall be included
   in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
   NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
   DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
   OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
   USE OR OTHER DEALINGS IN THE SOFTWARE. *)

(** Signatures of actions and their components. *)

open Base
open Act_common

(** Module type of random state modules.

    Each action takes in a random state record that can be:

    - converted to and from S-expressions;
    - generated by a QuickCheck generator, in the context of a fuzzer state. *)
module type S_random_state = sig
  type t [@@deriving sexp]
  (** The type of any random state on which this action depends. *)

  type subject
  (** The type of test subjects. *)

  val gen : subject -> t Base_quickcheck.Generator.t State.Monad.t
  (** [gen subject] is a stateful computation that, given subject [subject]
      and the current state, generates a random amount of random state for
      this fuzzer action. *)
end

module type Generic = sig
  type subject
  (** The type of test subjects. *)

  val name : Id.t
  (** The name of the action, as an act identifier. *)

  val readme : unit -> string
  (** [readme ()] builds a long synopsis of this action. *)

  val default_weight : int
  (** The default weight of the action. *)

  module Random_state : S_random_state with type subject := subject
  (** Random state on which this action depends. *)

  val available : subject -> bool State.Monad.t
  (** [available subject] is a stateful computation that, given subject
      [subject] and the current state, decides whether this action can run
      (given any member of [Random_state.t]). *)

  val run : subject -> Random_state.t -> subject State.Monad.t
  (** [run subject random] is a stateful computation that runs this action
      on [subject] with random state [random]. *)
end

module type S = Generic with type subject := Subject.Test.t
