(* The Automagic Compiler Tormentor

   Copyright (c) 2018--2019 Matt Windsor and contributors

   ACT itself is licensed under the MIT License. See the LICENSE file in the
   project root for more information.

   ACT is based in part on code from the Herdtools7 project
   (https://github.com/herd/herdtools7) : see the LICENSE.herd file in the
   project root for more information. *)

(** Fuzz metadata.

    This module defines a type for metadata records attached to parts of a
    fuzzer subject. Such metadata tracks:

    - whether a piece of code was generated by the fuzzer, or exists in the
      original subject;
    - whether a piece of code is regarded as 'dead code'. *)

(** {1 Metadata records} *)

type t [@@deriving compare, equal, sexp]

(** {2 Constructors} *)

val existing : t
(** [existing] is the base metadata for an existing item. *)

val generated : t
(** [generated] is the base metadata for a generated item. *)

val dead_code : t
(** [dead_code] is the base metadata for an item that has been both
    generated, and is dead-code by construction. *)

(** {2 Properties} *)

val is_dead_code : t -> bool
(** [is_dead_code md] gets whether the item to which [md] is attached is
    marked as dead code. Typically, only blocks that were generated as
    dead-by-construction will have this marker, and their contents will not
    (unless they were also generated in such a way). *)
