(* The Automagic Compiler Tormentor

   Copyright (c) 2018--2019 Matt Windsor and contributors

   ACT itself is licensed under the MIT License. See the LICENSE file in the
   project root for more information.

   ACT is based in part on code from the Herdtools7 project
   (https://github.com/herd/herdtools7) : see the LICENSE.herd file in the
   project root for more information. *)

(** Post-delitmus variable maps.

    These maps primarily associate Litmus IDs with the global
    symbols into which the delitmusifier has flattened them. *)

open Base

type t
(** Opaque type of variable maps. *)

val of_map : (Act_common.C_id.t option) Map.M(Act_common.Litmus_id).t -> t
(** [of_map map] creates a variable map from a [Base]-style map
    between Litmus variables and their optional global-scope
    C variable forms post-delitmus. *)

val global_c_variables : t -> Set.M(Act_common.C_id).t
(** [global_c_variables map] gets the set of global C variables
    generated by the delitmusifier over this variable map. *)
