#!/usr/bin/env bash
#  The Automagic Compiler Tormentor
#  Copyright (c) 2018--2020 Matt Windsor and contributors.
#  - ACT itself is licensed under the MIT License. See the LICENSE file in the
#    project root for more information.
#  - ACT is based in part on code from the Herdtools7 project
#    (https://github.com/herd/herdtools7) : see the LICENSE.herd file in the
#    project root for more information.

# Compiles the given litmus harness using the given compiler.
# Outputs the results to a binary stored locally, and echoes its name.

set -euo pipefail

declare ACT_STANDARD_FLAGS ACT_STANDARD_OPTS

SCRIPTDIR="${SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"}"
readonly SCRIPTDIR

# shellcheck source=scripts/act_bash/log.sh
source "${SCRIPTDIR}/act_bash/log.sh"
# shellcheck source=scripts/act_bash/args.sh
source "${SCRIPTDIR}/act_bash/args.sh"
# shellcheck source=scripts/act_bash/exec.sh
source "${SCRIPTDIR}/act_bash/exec.sh"


## Constants and arguments ##


# The name of the compiler to compile through.
# Must not be empty at the end of argument parsing.
COMPILER=""

# Whether or not we're running ACT programs through `dune exec`.
DUNE_EXEC="false"

# Whether or not verbose logging is enabled.
VERBOSE="false"


## Functions ##


# Prints the script's usage and exits.
usage() {
  echo "usage: $0 [-c COMPILER] [-${ACT_STANDARD_FLAGS}] HARNESS_DIR"
  echo
  echo "-c: ID of compiler to use to compile file"
  act::standard_usage

  exit 1
}


# The main function.
main() {
  while getopts "c:${ACT_STANDARD_OPTS}" a; do
    case ${a} in
      c) COMPILER=${OPTARG} ;;
      *) act::parse_standard_args "${a}" "${OPTARG:-}" ;;
    esac
  done

  # VERBOSE etc. are used indirectly by various library functions.
  # shellcheck disable=SC2034
  readonly COMPILER VERBOSE DUNE_EXEC
  shift $((OPTIND-1))

  if [[ -z ${COMPILER} ]]; then act::arg_error "expected a nonempty compiler (-c)"; fi
  if [[ $# -ne 1 ]]; then act::arg_error "expected precisely one anonymous argument"; fi

  readonly litdir="$1"

  readonly payload="${litdir}/a.out"
  touch payload

  act::compile -compiler "${COMPILER}" -mode binary "${litdir}"/*.c "${litdir}"/*.h -arg "pthread" -arg "std=gnu11" -o "${payload}"
  echo "${payload}"
}


## Entry point ##
main "$@"
