(* The Automagic Compiler Tormentor

   Copyright (c) 2018--2019 Matt Windsor and contributors

   ACT itself is licensed under the MIT License. See the LICENSE file in the
   project root for more information.

   ACT is based in part on code from the Herdtools7 project
   (https://github.com/herd/herdtools7) : see the LICENSE.herd file in the
   project root for more information. *)

(** Mini-model: variable typing environments

    Large parts of the mini-model's type checking and program fragment
    generation functionality depends on the existence of a typing environment
    mapping variable names to their {{!Type} mini-model types}. This module,
    and its accompanying {{!Env_types} types module}, provide a modular
    interface for these typing environments.

    Usually, the typing environments will be built as first-class modules,
    generated by applying {{!Make} Make} to a lifted map value. *)

open Base

(** [Make (E)] extends a basic environment module with various functions and
    generators. *)
module Make (E : sig
  val env : Type.t Map.M(Act_common.C_id).t
end) : Env_types.S

(** [Make_with_known_values (E)] extends a basic environment module with various functions and
    generators. *)
module Make_with_known_values (E : sig
  val env : Type.t Map.M(Act_common.C_id).t

  val known_values : Constant.t Map.M(Act_common.C_id).t
end) : Env_types.S_with_known_values
