#!/usr/bin/env bash
# Adds an include for the first argument to the Litmus file given by the second argument.

set -o errexit
set -o pipefail
set -o nounset

# TODO(@MattWindsor91): make this more robust?

# The `sed` binary to use; this can be overrode using shell/environment variables.
readonly sed=${SED="sed"}

readonly hfile="$1"
readonly litfile="$2"

# shellcheck disable=SC1004
"${sed}" '
/#include "utils.h"/ a\
#include "'"${hfile}"'"
' "${litfile}" > "${litfile}.new"
mv "${litfile}.new" "${litfile}"
