#!/usr/bin/env bash
# Quick script to make sure the various ACT commands are installed.

set -o errexit
set -o pipefail
set -o nounset

SCRIPTDIR="${SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
# shellcheck source=scripts/act_bash/exec.sh
source "${SCRIPTDIR}/act_bash/exec.sh"

act::backend -help >/dev/null
act::delitmus -help >/dev/null
