#!/usr/bin/env bash
# Given a C litmus test and its fuzzed equivalent, this script checks
# to see if the behaviours of one are included in the behaviours of the other.
#
# For usage information, scroll down to the `usage` function.

set -o errexit
set -o pipefail
set -o nounset

SCRIPTDIR="${SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
readonly SCRIPTDIR

# shellcheck source=scripts/act_bash/args.sh
source "${SCRIPTDIR}/act_bash/args.sh"
# shellcheck source=scripts/act_bash/exec.sh
source "${SCRIPTDIR}/act_bash/exec.sh"
# shellcheck source=scripts/act_bash/log.sh
source "${SCRIPTDIR}/act_bash/log.sh"


## Constants and arguments ##


# The backend ID to use to get state sets.
BACKEND="herd"

# The name of the compiler to compile through (using c_litmus_indirect).
# If empty, we don't compile, we just run straight through the backend.
COMPILER=""

# Whether or not we're running ACT programs through `dune exec`.
DUNE_EXEC="false"

# Whether or not verbose logging is enabled.
VERBOSE="false"


## Functions ##


# Prints usage information and exits.
usage() {
  echo "Usage: $0 [-b BACKEND] [-c COMPILER] [-qvxh?] ORIGINAL_FILE FUZZED_FILE"
  echo
  echo "-b: ID of backend to use for checking C files"
  echo "-c: ID of compiler to use (if given, c_litmus_indirect is used)"
  echo "-v/-q: verbose/quiet"
  echo "-x: run ACT binaries with \`dune exec\`"
  echo "-h/-?: usage"
  exit
}


main() {
  while getopts "b:c:qvx?h" a; do
    case ${a} in
    b) act::set_nz "b" "BACKEND" "${OPTARG}" ;;
    c) COMPILER=${OPTARG} ;;
    q) VERBOSE="false" ;;
    v) VERBOSE="true" ;;
    x) DUNE_EXEC="true" ;;
    h|?) usage ;;
    esac
  done
  readonly BACKEND COMPILER DUNE_EXEC VERBOSE
  shift $((OPTIND-1))

  act::check_dune_exec
  if [[ $# -ne 2 ]]; then act::arg_error "${0}: need precisely two file arguments"; fi

  local original_file=$1
  local fuzzed_file=$2

  local flags
  flags="$(act::flags_qvx)"
  act::state compare -hum \
    <("${SCRIPTDIR}/c_states" -b "${BACKEND}" -c "${COMPILER}" "${flags}" "${original_file}") \
    <("${SCRIPTDIR}/c_states" -b "${BACKEND}" -c "${COMPILER}" "${flags}" "${fuzzed_file}")
}


## Entry point ##
main "${@}"
