#!/usr/bin/env bash
#
# Converts a single C litmus test to an assembly litmus test.

set -o errexit
set -o pipefail
set -o nounset

SCRIPTDIR="${SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
# shellcheck source=scripts/act_bash/exec.sh
source "${SCRIPTDIR}/act_bash/exec.sh"
# shellcheck source=scripts/act_bash/log.sh
source "${SCRIPTDIR}/act_bash/log.sh"
# shellcheck source=scripts/act_bash/naming.sh
source "${SCRIPTDIR}/act_bash/naming.sh"


OUTPUT_DIR=""


usage() {
	echo "usage: $0 COMPILER LIT_FILE"
	exit 1
}

main() {
  if [[ $# -ne 2 ]]; then usage; fi

  local compiler="$1"
  local lit_file="$2"

  act::setup_temp_output_dir # into OUTPUT_DIR
  local auxfile="${OUTPUT_DIR}/aux.json"
  local cfile="${OUTPUT_DIR}/out.c"
  local sfile="${OUTPUT_DIR}/out.s"

  act::delitmus -aux "${auxfile}" "${lit_file}" -o "${cfile}"
  act::compile -compiler "${compiler}" "${cfile}" -o "${sfile}"
  act::litmusify -compiler "${compiler}" -aux "${auxfile}" "${sfile}"
}

## Entry point ##
main "$@"
