#!/usr/bin/env bash
#
# Converts a single C litmus test to an assembly litmus test.

set -o errexit
set -o pipefail
set -o nounset

ACT="${ACT="act"}"

usage() {
	echo "usage: $0 COMPILER LIT_FILE"
	exit 1
}

if [[ $# -ne 2 ]]; then
	usage
fi

compiler="$1"
lit_file="$2"

# Most other invocations of mktemp aren't portable.
tmpdir="$(mktemp -d)" || exit
trap 'rm -r "${tmpdir}"' EXIT

auxfile="${tmpdir}/aux.json"
cfile="${tmpdir}/out.c"
sfile="${tmpdir}/out.s"

"${ACT}" c delitmus -aux "${auxfile}" "${lit_file}" -o "${cfile}"
"${ACT}" c compile -compiler "${compiler}" "${cfile}" -o "${sfile}"
"${ACT}" asm litmusify -compiler "${compiler}" -aux "${auxfile}" "${sfile}"

