#!/usr/bin/env bash
#
# A driver that works by running Litmus on a stubbed-out version of
# a litmus test in cross-compile mode, then generates an object file
# containing the body of the litmus test and links it into the
# Litmus harness.
#
# This script is a wrapper around `obj_splitmus_gen`.

set -o errexit
set -o pipefail
set -o nounset

SCRIPTDIR="${SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"

# Programs
ACT=${ACT="act"}
LITMUS=${LITMUS="litmus7"}
SED=${SED="sed"}

# Prints the script's usage and exits.
usage() {
  echo "usage: $0 LITMUS_ID COMPILER_ID FILE" >&2
  exit 1
}

# Parameters
[[ "$#" -ne "3" ]] && usage
backend="$1"
compiler="$2"
infile="$3"
name="$("${SCRIPTDIR}/litmus_test_name" "${infile}")"

tmpdir="$(mktemp -d)" || exit 2
"${SCRIPTDIR}/obj_splitmus_gen" "${backend}" "${compiler}" "${infile}" "${name}" "${tmpdir}" > /dev/null
rm -r "${tmpdir}"
