#!/usr/bin/env python3
# The Automagic Compiler Tormentor
#
# Copyright (c) 2018--2019 Matt Windsor and contributors
#
# ACT itself is licensed under the MIT License. See the LICENSE file in the
# project root for more information.
#
# ACT is based in part on code from the Herdtools7 project
# (https://github.com/herd/herdtools7) : see the LICENSE.herd file in the
# project root for more information. *)

import argparse
import json
from act_py import test_runner

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("test", type=str, help="The input test file.")
    args = parser.parse_args()

    with open(args.test) as fp:
        test = test_runner.test_from_dict(json.load(fp))
    test.run()
