(* The Automagic Compiler Tormentor

   Copyright (c) 2018--2019 Matt Windsor and contributors

   ACT itself is licensed under the MIT License. See the LICENSE file in the
   project root for more information.

   ACT is based in part on code from the Herdtools7 project
   (https://github.com/herd/herdtools7) : see the LICENSE.herd file in the
   project root for more information. *)

(** A command that generates reflexive location maps for use in the state
    diff part of ACT.

    Such location maps are useful for diffing C litmus tests against
    modifications of themselves---for example, those generated by the ACt
    fuzzer. *)

val command : Core_kernel.Command.t
(** [command] is the top-level command for generating reflexive location
    maps. *)
